export const FETCH_MACHINES = 'FETCH_MACHINES';
export const FETCH_MACHINES_SUCCESS = 'FETCH_MACHINES_SUCCESS';
export const FETCH_MACHINE = 'FETCH_MACHINE';
export const FETCH_MACHINE_SUCCESS = 'FETCH_MACHINE_SUCCESS';
export const HEALTH_UPDATE = 'HEALTH_UPDATE';
